name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build applications
      run: npm run build:prod
      env:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{'pk_test_dHJ1c3RlZC1kdWNrbGluZy00My5jbGVyay5hY2NvdW50cy5kZXYk'}}
        CLERK_SECRET_KEY: ${{'sk_test_TsgGRcqT8xXMBwnKthRw6tQz3tOVxWJYuYaCNRHzxl'}}
        NEXT_PUBLIC_API_URL: ${{ 'https://sbroshrhero.com/api' }}
    
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/apps/frontend/
        server-dir: /public_html/